openapi: 3.0.0
info:
  title: Calendarium Backend

  description: API for Calendarium Backend
  version: 1.1.0
  
servers:
  - url: http://127.0.0.1:44000/api # ToDo
    variables: {}
    description: Test Server Backend
    
  - url: www.google.com  # ToDo
    variables: {}
    description: Production Server Backend
    
paths:

  # Authentication
  /APISignUp:
    post:
      summary: Create a new user
      tags:
        - Authentication
      requestBody:
        content:
          application/json:
            example:
              first_name: str
              last_name: str
              username: str
              email: str
              password: str
      responses:
        '201':
          description: User created successfully
          
  /APIActivateAccount:
    get:
      summary: activate acount
      tags:
        - Authentication
      parameters:
        - name: token
          in: query
          description: Token Provided in email sent to user
          required: true
          schema:
            type: string 
            
      responses:
        '200':
          description: User Activated
          
        '401':
          description: User Invalid
          
  /APISignIn:
    post:
      summary: Identify User
      tags:
        - Authentication
      requestBody:
        content:
          application/json:
            example:
              username: str
              password: str
      responses:
        '200':
          description: User Authenticated
  
        '401':
          description: Password is wrong
          
  /APIChangePassword:
    put:
      summary: Changes The Password of the user
      tags:
        - Authentication
        
      parameters:
        - name: token
          in: query
          description: Token Provided  at SignIn
          required: true
          schema:
            type: string 
            
      requestBody:
        content:
          application/json:
            example:
              old_password: str
              new_password: str
      responses:
        '200':
          description: User Authenticated
        
        '401':
          description: Password is wrong
          
  /APIResetPassword:
    post:
      summary: Identify User
      tags:
        - Authentication
      requestBody:
        content:
          application/json:
            example:
              username: str
      responses:
        '200':
          description: Reset Email sent to user
          
  /APIDeleteAccount:
    delete:
      summary: Add a new account to system
      tags:
        - Authentication
        
      responses:
        '200':
          description: Subscription added successfully
            
  # Subscriptions
  /APIGetSubscriptionStatus:
    get:
      summary: create subscription for user
      tags:
        - Payments
      parameters:
        - name: token
          in: query
          description: Token Provided at sign in
          required: true
          schema:
            type: string 
      responses:
        '200':
          description: Subscription added successfully
          
  /APICreateSubscription:
    post:
      summary: create subscription for user
      tags:
        - Payments
      parameters:
        - name: token
          in: query
          description: Token Provided at sign in
          required: true
          schema:
            type: string 
      requestBody:
        content:
          application/json:
            example:
              user_id: str
              subscriotion_type: str
              payment_token: str
              # ToDo
      responses:
        '200':
          description: Subscription added successfully
          
  /APICancelSubscription:
    delete:
      summary: Cancel Service
      tags:
        - Payments
      parameters:
        - name: token
          in: query
          description: Token Provided at sign in
          required: true
          schema:
            type: string 
      responses:
        '200':
          description: Subscription added successfully
        
        '404':
          description: User not found
          
  # Accounts Manager
  /APIGetSercivesAccountsData:
    get:
      summary: Cancel Service
      tags:
        - Accounts Manager
      parameters:
        - name: token
          in: query
          description: Token Provided at sign in
          required: true
          schema:
            type: string 
      responses:
        '200':
          description: Subscription added successfully
        
        '404':
          description: User not found
          
  /APIAddServiceAccount:
    post:
      summary: Add a new account to system
      tags:
        - Accounts Manager
      parameters:
        - name: token
          in: query
          description: Token Provided at sign in
          required: true
          schema:
            type: string 
      requestBody:
        content:
          application/json:
            example:
              user_id: str
              password: str
      responses:
        '200':
          description: Subscription added successfully
        
        '404':
          description: User not found
          
  /APIDeleteServiceAccount:
    delete:
      summary: Add a new account to system
      tags:
        - Accounts Manager
        
      parameters:
        - name: token
          in: query
          description: Token Provided at sign in
          required: true
          schema:
            type: string 
        
      responses:
        '200':
          description: Subscription added successfully
    
          
  
  

